server:
  port: 8796


spring:
  application:
    name: service-feign-hystrix


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8791/eureka/


feign:
  hystrix:
    enabled: true  #feign自带断路器，但需要打开